// playgrounds/react/src/inputs/InputCheckbox.jsx
import React from 'react';
import PropTypes from 'prop-types';
import useField from '@validate-me/react/useField';

export default function InputCheckbox(props) {
  const [field, inputProps] = useField('checkbox', props);

  return (
    <div>
      <label>
        <input {...inputProps} />
        {props.label}
      </label>
      <p style={{ minHeight: '1.15em' }}>
        {!field.pristine && field.error && (
          <span style={{ color: 'red' }}>{field.error}</span>
        )}
        {!field.error && field.warning && (
          <span style={{ color: 'orange' }}>{field.warning}</span>
        )}
      </p>
    </div>
  );
}

InputCheckbox.propTypes = {
  form: PropTypes.any.isRequired,
  label: PropTypes.string.isRequired,
  name: PropTypes.string.isRequired,
  value: PropTypes.string,
};

// playgrounds/vue/src/InputCheckbox.vue
<template>
  <div>
    <label>
      <input
        v-validate-me
        :name="name"
        :checked="value"
        :autofocus="autofocus"
        type="checkbox"
      />
      {{ label }}
    </label>
    <p style="min-height: 1.15em">
      <span v-show="!pristine && error" style="color: red">{{ error }}</span>
      <span v-show="!error && warning" style="color: orange">{{
        warning
      }}</span>
    </p>
  </div>
</template>

<script>
import VueTypes from 'vue-types';
import FieldMixin from '@validate-me/vue/FieldMixin';

export default {
  mixins: [FieldMixin],
  props: {
    label: VueTypes.string.isRequired,
    autofocus: Boolean,
  },
};
</script>
