// playgrounds/react/src/inputs/InputSelect.jsx
import React from 'react';
import PropTypes from 'prop-types';
import useField from '@validate-me/react/useField';

import LabelWrapper from './wrappers/LabelWrapper';

export default function InputSelect(props) {
  const [field, inputProps] = useField('select', props);

  return (
    <LabelWrapper label={props.label} field={field}>
      <select {...inputProps} value={inputProps.value}>
        <option value="" disabled>
          Select an option
        </option>
        {Object.keys(props.options).map(key => (
          <option key={key} value={key}>
            {props.options[key]}
          </option>
        ))}
      </select>
    </LabelWrapper>
  );
}

InputSelect.propTypes = {
  label: PropTypes.string.isRequired,
  name: PropTypes.string.isRequired,
  options: PropTypes.objectOf(PropTypes.string),
  required: PropTypes.bool,
  value: PropTypes.string,
};

// playgrounds/vue/src/inputs/InputSelect.vue
<template>
  <LabelWrapper :label="label" :field="vField">
    <select
      v-validate-me
      :name="name"
      :value="vField.value"
      :required="required"
    >
      <option value="" disabled>Select an option</option>
      <option v-for="(option, key) in options" :key="key" :value="key">{{
        option
      }}</option>
    </select>
  </LabelWrapper>
</template>

<script>
import VueTypes from 'vue-types';
import FieldMixin from '@validate-me/vue/FieldMixin';

import LabelWrapper from './wrappers/LabelWrapper';

export default {
  components: {
    LabelWrapper,
  },
  mixins: [FieldMixin],
  props: {
    label: VueTypes.string.isRequired,
    options: VueTypes.objectOf(String).isRequired,
    autofocus: Boolean,
  },
};
</script>
