// playgrounds/react/src/inputs/InputCheckboxList.jsx
import React from 'react';
import PropTypes from 'prop-types';
import useField from '@validate-me/react/useField';

import NonLabelWrapper from './wrappers/NonLabelWrapper';

export default function InputCheckboxList(props) {
  const [field, inputProps] = useField('checkbox', props);

  return (
    <NonLabelWrapper field={field}>
      <h3>{props.label}</h3>
      {Object.keys(props.options).map(key => (
        <label key={key}>
          <input
            {...inputProps}
            value={key}
            checked={inputProps.value[key] || false}
          />
          {props.options[key]}
        </label>
      ))}
    </NonLabelWrapper>
  );
}

InputCheckboxList.propTypes = {
  label: PropTypes.string.isRequired,
  name: PropTypes.string.isRequired,
  options: PropTypes.objectOf(PropTypes.string),
  value: PropTypes.objectOf(PropTypes.bool),
};

// playgrounds/vue/src/inputs/InputCheckboxList.vue
<template>
  <NonLabelWrapper :field="vField">
    <h3>{{ label }}</h3>
    <label v-for="(option, key) in options" :key="key">
      <input
        v-validate-me
        :name="name"
        :value="key"
        type="checkbox"
        :checked="vField.value[key]"
      />{{ option }}</label
    >
  </NonLabelWrapper>
</template>

<script>
import VueTypes from 'vue-types';
import FieldMixin from '@validate-me/vue/FieldMixin';

import NonLabelWrapper from './wrappers/NonLabelWrapper';

export default {
  components: {
    NonLabelWrapper,
  },
  mixins: [FieldMixin],
  props: {
    label: VueTypes.string.isRequired,
    options: VueTypes.objectOf(String).isRequired,
    checked: VueTypes.objectOf(Boolean).def({}),
    autofocus: Boolean,
  },
};
</script>
