// playgrounds/react/src/inputs/InputRadioList.jsx
import React from 'react';
import PropTypes from 'prop-types';
import useField from '@validate-me/react/useField';

import NonLabelWrapper from './wrappers/NonLabelWrapper';

export default function InputRadioList(props) {
  const [field, inputProps] = useField('radio', props);

  return (
    <NonLabelWrapper field={field}>
      <h3>{props.label}</h3>
      {Object.keys(props.options).map(key => (
        <label key={key}>
          <input
            {...inputProps}
            value={key}
            checked={inputProps.value === key}
          />
          {props.options[key]}
        </label>
      ))}
    </NonLabelWrapper>
  );
}

InputRadioList.propTypes = {
  label: PropTypes.string.isRequired,
  name: PropTypes.string.isRequired,
  options: PropTypes.objectOf(PropTypes.string),
  required: PropTypes.bool,
  value: PropTypes.string,
};

// playgrounds/vue/src/inputs/InputRadioList.vue
<template>
  <NonLabelWrapper :field="vField">
    <label v-for="(option, key) in options" :key="key">
      <input
        v-validate-me
        :name="name"
        :value="key"
        type="radio"
        :checked="vField.value === key"
      />
      {{ option }}
    </label>
  </NonLabelWrapper>
</template>

<script>
import VueTypes from 'vue-types';
import FieldMixin from '@validate-me/vue/FieldMixin';

import NonLabelWrapper from './wrappers/NonLabelWrapper';

export default {
  components: {
    NonLabelWrapper,
  },
  mixins: [FieldMixin],
  props: {
    label: VueTypes.string.isRequired,
    options: VueTypes.objectOf(String).isRequired,
    checked: String,
    autofocus: Boolean,
  },
};
</script>
