// playgrounds/react/src/inputs/InputText.jsx
import React from 'react';
import PropTypes from 'prop-types';
import useField from '@validate-me/react/useField';

import LabelWrapper from './wrappers/LabelWrapper';

export default function InputText(props) {
  const [field, inputProps] = useField('text', props);

  return (
    <LabelWrapper label={props.label} field={field}>
      <input {...inputProps} />
    </LabelWrapper>
  );
}

InputText.propTypes = {
  rules: PropTypes.arrayOf(PropTypes.arrayOf(PropTypes.string)),
  label: PropTypes.string.isRequired,
  name: PropTypes.string.isRequired,
  value: PropTypes.string,
  required: PropTypes.bool,
};

// playgrounds/vue/src/inputs/InputText.vue
<template>
  <LabelWrapper :label="label" :field="vField">
    <input
      v-validate-me="rules"
      :name="name"
      :value="vField.value"
      :autofocus="autofocus"
      :required="required"
    />
  </LabelWrapper>
</template>

<script>
import VueTypes from 'vue-types';
import FieldMixin from '@validate-me/vue/FieldMixin';

import LabelWrapper from './wrappers/LabelWrapper';

export default {
  components: {
    LabelWrapper,
  },
  mixins: [FieldMixin],
  props: {
    label: VueTypes.string.isRequired,
    rules: VueTypes.arrayOf(VueTypes.arrayOf(String)),
    autofocus: Boolean,
  },
};
</script>
