// playgrounds/vue/src/inputs/InputDate.vue
<template>
  <LabelWrapper :label="label" :field="vField">
    <input
      v-validate-me
      :name="name"
      :value="vField.value"
      :min="min"
      :max="max"
      :type="type"
    />
  </LabelWrapper>
</template>

<script>
import VueTypes from 'vue-types';
import FieldMixin from '@validate-me/vue/FieldMixin';

import LabelWrapper from './wrappers/LabelWrapper';

const types = ['date', 'time', 'datetime-local', 'week', 'month'];

export default {
  components: {
    LabelWrapper,
  },
  mixins: [FieldMixin],
  props: {
    label: VueTypes.string.isRequired,
    autofocus: Boolean,
    min: String,
    max: String,
    type: {
      validator: type => types.includes(type),
      required: true,
    },
  },
};
</script>

// playgrounds/react/src/inputs/InputDate.jsx
import React from 'react';
import PropTypes from 'prop-types';
import useField from '@validate-me/react/useField';

import LabelWrapper from './wrappers/LabelWrapper';

export default function InputDate(props) {
  const [field, inputProps] = useField(props.type, props);

  return (
    <LabelWrapper label={props.label} field={field}>
      <input {...inputProps} />
    </LabelWrapper>
  );
}

InputDate.propTypes = {
  type: PropTypes.oneOf(['date', 'time', 'datetime-local', 'week', 'month']),
  min: PropTypes.string,
  max: PropTypes.string,
  label: PropTypes.string.isRequired,
  name: PropTypes.string.isRequired,
  value: PropTypes.string,
  required: PropTypes.bool,
};
