// playgrounds/vue/src/InputSelect.vue
<template>
  <div>
    <h3>{{ label }}</h3>
    <select
      v-validate-me
      :name="name"
      :value="vField.value"
      :required="required"
    >
      <option value="" disabled>Select an option</option>
      <option v-for="(option, key) in options" :key="key" :value="key">{{
        option
      }}</option>
    </select>
    <p style="min-height: 1.15em">
      <span v-show="vField.touched && vField.error" style="color: red">{{
        vField.error
      }}</span>
      <span v-show="!vField.error && vField.warning" style="color: orange">{{
        vField.warning
      }}</span>
    </p>
  </div>
</template>

<script>
import VueTypes from 'vue-types';
import FieldMixin from '@validate-me/vue/FieldMixin';

export default {
  mixins: [FieldMixin],
  props: {
    label: VueTypes.string.isRequired,
    options: VueTypes.objectOf(String).isRequired,
    autofocus: Boolean,
  },
};
</script>

// playgrounds/react/src/inputs/InputSelect.jsx
import React from 'react';
import PropTypes from 'prop-types';
import useField from '@validate-me/react/useField';

export default function InputSelect(props) {
  const [field, inputProps] = useField('select', props);

  return (
    <div>
      <h3>{props.label}</h3>
      <select {...inputProps} value={inputProps.value}>
        <option value="" disabled>
          Select an option
        </option>
        {Object.keys(props.options).map(key => (
          <option key={key} value={key}>
            {props.options[key]}
          </option>
        ))}
      </select>
      <p style={{ minHeight: '1.15em' }}>
        {field.touched && field.error && (
          <span style={{ color: 'red' }}>{field.error}</span>
        )}
        {!field.error && field.warning && (
          <span style={{ color: 'orange' }}>{field.warning}</span>
        )}
      </p>
    </div>
  );
}

InputSelect.propTypes = {
  label: PropTypes.string.isRequired,
  name: PropTypes.string.isRequired,
  options: PropTypes.objectOf(PropTypes.string),
  required: PropTypes.bool,
  value: PropTypes.string,
};
