// playgrounds/vue/src/inputs/InputEmail.vue
<template>
  <LabelWrapper :label="label" :field="vField">
    <input
      v-validate-me="rules"
      type="email"
      :name="name"
      :value="vField.value"
      :autofocus="autofocus"
      :required="required"
      :multiple="multiple"
      :pattern="pattern"
    />
  </LabelWrapper>
</template>

<script>
import VueTypes from 'vue-types';
import FieldMixin from '@validate-me/vue/FieldMixin';

import LabelWrapper from './wrappers/LabelWrapper';

export default {
  components: {
    LabelWrapper,
  },
  mixins: [FieldMixin],
  props: {
    label: VueTypes.string.isRequired,
    rules: VueTypes.arrayOf(VueTypes.arrayOf(String)),
    autofocus: Boolean,
    multiple: Boolean,
    pattern: String,
  },
};
</script>

// playgrounds/react/src/inputs/InputEmail.jsx
import React from 'react';
import PropTypes from 'prop-types';
import useField from '@validate-me/react/useField';

import LabelWrapper from './wrappers/LabelWrapper';

export default function InputEmail(props) {
  const [field, inputProps] = useField('email', props);

  return (
    <LabelWrapper label={props.label} field={field}>
      <input {...inputProps} />
    </LabelWrapper>
  );
}

InputEmail.propTypes = {
  rules: PropTypes.arrayOf(PropTypes.arrayOf(PropTypes.string)),
  label: PropTypes.string.isRequired,
  name: PropTypes.string.isRequired,
  value: PropTypes.string,
  multiple: PropTypes.bool,
  pattern: PropTypes.string,
  required: PropTypes.bool,
};
