// playgrounds/vue/src/InputDate.vue
<template>
  <div>
    <h3>{{ label }}</h3>
    <input
      v-validate-me
      :name="name"
      :value="value"
      :min="min"
      :max="max"
      :type="type"
    />
    <p style="min-height: 1.15em">
      <span v-show="vField.touched && vField.error" style="color: red">{{
        vField.error
      }}</span>
      <span v-show="!vField.error && vField.warning" style="color: orange">{{
        vField.warning
      }}</span>
    </p>
  </div>
</template>

<script>
import VueTypes from 'vue-types';
import FieldMixin from '@validate-me/vue/FieldMixin';

const types = ['date', 'time', 'datetime-local', 'week', 'month'];

export default {
  mixins: [FieldMixin],
  props: {
    label: VueTypes.string.isRequired,
    autofocus: Boolean,
    min: String,
    max: String,
    type: {
      validator: type => types.includes(type),
      required: true,
    },
  },
};
</script>

// playgrounds/react/src/inputs/InputDate.jsx
import React from 'react';
import PropTypes from 'prop-types';
import useField from '@validate-me/react/useField';

export default function InputDate(props) {
  const [field, inputProps] = useField(props.type, props);

  return (
    <div>
      <h3>{props.label}</h3>
      <input {...inputProps} />
      <p style={{ minHeight: '1.15em' }}>
        {field.touched && field.error && (
          <span style={{ color: 'red' }}>{field.error}</span>
        )}
        {!field.error && field.warning && (
          <span style={{ color: 'orange' }}>{field.warning}</span>
        )}
      </p>
    </div>
  );
}

InputDate.propTypes = {
  type: PropTypes.oneOf(['date', 'time', 'datetime-local', 'week', 'month']),
  min: PropTypes.string,
  max: PropTypes.string,
  label: PropTypes.string.isRequired,
  name: PropTypes.string.isRequired,
  value: PropTypes.string,
  required: PropTypes.bool,
};
