// playgrounds/vue/src/inputs/InputCheckbox.vue
<template>
  <NonLabelWrapper :field="vField">
    <label>
      <input
        v-validate-me
        :name="name"
        :checked="vField.value"
        :autofocus="autofocus"
        type="checkbox"
      />
      {{ label }}
    </label>
  </NonLabelWrapper>
</template>

<script>
import VueTypes from 'vue-types';
import FieldMixin from '@validate-me/vue/FieldMixin';

import NonLabelWrapper from './wrappers/NonLabelWrapper';

export default {
  components: {
    NonLabelWrapper,
  },
  mixins: [FieldMixin],
  props: {
    label: VueTypes.string.isRequired,
    autofocus: Boolean,
    checked: Boolean,
  },
};
</script>

// playgrounds/react/src/inputs/InputCheckbox.jsx
import React from 'react';
import PropTypes from 'prop-types';
import useField from '@validate-me/react/useField';

import NonLabelWrapper from './wrappers/NonLabelWrapper';

export default function InputCheckbox(props) {
  const [field, inputProps] = useField('checkbox', props);

  return (
    <NonLabelWrapper field={field}>
      <label>
        <input {...inputProps} /> {props.label}
      </label>
    </NonLabelWrapper>
  );
}

InputCheckbox.propTypes = {
  label: PropTypes.string.isRequired,
  name: PropTypes.string.isRequired,
  value: PropTypes.bool,
  required: PropTypes.bool,
};
