// playgrounds/react/src/inputs/wrappers/LabelWrapper.jsx
import React from 'react';
import PropTypes from 'prop-types';

export default function LabelWrapper({ label, field, children }) {
  return (
    <label>
      <h3>{label}</h3>
      {children}
      <p style={{ minHeight: '1.15em' }}>
        {field.touched && field.error && (
          <span style={{ color: 'red' }}>{field.error}</span>
        )}
        {!field.error && field.warning && (
          <span style={{ color: 'orange' }}>{field.warning}</span>
        )}
      </p>
    </label>
  );
}

LabelWrapper.propTypes = {
  label: PropTypes.string.isRequired,
  field: PropTypes.any.isRequired,
  children: PropTypes.oneOf([
    PropTypes.element,
    PropTypes.arrayOf(PropTypes.element),
  ]).isRequired,
};

// playgrounds/vue/src/inputs/wrappers/LabelWrapper.vue
<template>
  <label>
    <h3>{{ label }}</h3>
    <scope />
    <p style="min-height: 1.15em">
      <span v-show="field.touched && field.error" style="color: red">{{
        field.error
      }}</span>
      <span v-show="!field.error && field.warning" style="color: orange">{{
        field.warning
      }}</span>
    </p>
  </label>
</template>

<script>
import VueTypes from 'vue-types';

export default {
  props: {
    label: VueTypes.string.isRequired,
    field: VueTypes.any.isRequired,
  },
};
</script>
