// playgrounds/vue/src/inputs/wrappers/NonLabelWrapper.vue
<template>
  <div>
    <scope />
    <p style="min-height: 1.15em">
      <span v-show="field.touched && field.error" style="color: red">{{
        field.error
      }}</span>
      <span v-show="!field.error && field.warning" style="color: orange">{{
        field.warning
      }}</span>
    </p>
  </div>
</template>

<script>
import VueTypes from 'vue-types';

export default {
  props: {
    field: VueTypes.any.isRequired,
  },
};
</script>

// playgrounds/react/src/inputs/wrappers/NonLabelWrapper.jsx
import React from 'react';
import PropTypes from 'prop-types';

export default function NonLabelWrapper({ field, children }) {
  return (
    <div>
      {children}
      <p style={{ minHeight: '1.15em' }}>
        {field.touched && field.error && (
          <span style={{ color: 'red' }}>{field.error}</span>
        )}
        {!field.error && field.warning && (
          <span style={{ color: 'orange' }}>{field.warning}</span>
        )}
      </p>
    </div>
  );
}

NonLabelWrapper.propTypes = {
  field: PropTypes.any.isRequired,
  children: PropTypes.oneOf([
    PropTypes.element,
    PropTypes.arrayOf(PropTypes.element),
  ]).isRequired,
};
